model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: float32  
attn_implementation: eager  
bf16: false  
use_cpu: true  

max_steps: 20  
per_device_train_batch_size: 2  
gradient_accumulation_steps: 4  
gradient_checkpointing: true  
gradient_checkpointing_kwargs:
  use_reentrant: false
max_grad_norm: 1.0

max_prompt_length: 128  # 适当增加但仍需控制内存
max_completion_length: 128
min_completion_length: 32  # 防止生成过短无效内容

dataloader_num_workers: 6  
dataloader_pin_memory: false  
dataloader_prefetch_factor: 2

learning_rate: 3e-5  
lr_scheduler_type: linear
warmup_ratio: 0.1  
optim: adamw_torch
weight_decay: 0.01

max_samples_in_memory: 1000  
torch_compile: false  

logging_steps: 5
eval_steps: 20
save_steps: 50
report_to: none  
disable_tqdm: false  
