# Model arguments
model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat32
attn_implementation: flash_attention_2
bf16: true
tf32: false

# Training arguments
max_steps: 35
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false  
max_grad_norm: 1.0

# Memory optimization
max_prompt_length: 128
max_completion_length: 128
vllm_gpu_memory_utilization: 0.5  
dataloader_num_workers: 0
dataloader_pin_memory: false
