model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: float32
attn_implementation: eager
bf16: false
tf32: false

max_steps: 10
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false  
max_grad_norm: 1.0

max_prompt_length: 128
max_completion_length: 128
dataloader_num_workers: 4
dataloader_pin_memory: false

use_cpu: true
ddp_find_unused_parameters: false
